name: Build and Deploy

on:
  push:
    tags:
      - '*'  # Trigger the workflow for any tag push
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build Application
      run: |
        echo "Building the application with Maven..."
        mvn clean package
    
    - name: Check Build Directory
      run: |
        echo "Listing contents of the build directory..."
        ls -la target
    
    - name: Package Application
      run: |
        echo "Packaging the application..."
        if [ -d "target" ]; then
          tar -czf app.tar.gz target/
        else
          echo "Error: Target directory 'target/' does not exist"
          exit 1
        fi
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: application
    
    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
    
    - name: Deploy to Repository
      env:
        TARGET_REPO: ${{ secrets.TARGET_REPO }}
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
      run: |
        echo "Deploying the application..."
        git clone https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO }}.git target-repo
        mv app.tar.gz target-repo/
        cd target-repo
        git add app.tar.gz
        git commit -m "Add new build"
        git push

